name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1

    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        conda-channels: conda-forge

    - name: Fix missing libudev.so.0 on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        wget http://mirrors.kernel.org/ubuntu/pool/main/u/udev/libudev0_175-0ubuntu9_amd64.deb
        sudo dpkg -i libudev0_175-0ubuntu9_amd64.deb

    - name: Conda install dependencies
      run: conda install python=${{ matrix.python-version }} pip setuptools sfml pybind11 pytest

    - name: Install pysfml11
      run: pip -vvv install .

    - name: Run tests
      if: matrix.os != 'windows-latest' || matrix.python-version == 3.6
      run: pytest -vvv tests --ci True
