name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true

    - name: Fix missing libudev.so.0 on Linux
      shell: pwsh
      if: matrix.os == 'ubuntu-latest'
      run: |
        wget http://mirrors.kernel.org/ubuntu/pool/main/u/udev/libudev0_175-0ubuntu9_amd64.deb
        sudo dpkg -i libudev0_175-0ubuntu9_amd64.deb

    - name: Conda install dependencies
      shell: pwsh
      run: conda install -c conda-forge python=${{ matrix.python-version }} pip setuptools sfml pybind11 pytest

    - name: Debug
      shell: pwsh
      run: python setup.py egg_info

    - name: Install pysfml11
      shell: pwsh
      run: |
        pip --version
        pip -vvv install .

    - name: Run tests
      shell: pwsh
      run: pytest -vvv tests --ci True
