name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash -l {0}

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge

    - name: Fix missing libudev.so.0 on Linux (this is not the recommended way)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt install libudev-dev
        sudo ln -sf /lib/$(arch)-linux-gnu/libudev.so.1 /lib/$(arch)-linux-gnu/libudev.so.0

    - name: Conda install dependencies
      run: mamba install python=${{ matrix.python-version }} pip setuptools sfml=2.5 pybind11 pytest

    - name: Install pysfml11
      run: pip -vvv install .

    - name: Run tests
      run: pytest -vvv tests --ci True
