name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash -l {0}

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install mamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yml
        environment-name: pysfml11
        extra-specs: |
            python=${{ matrix.python-version }}

    - name: Install pysfml11
      run: pip -vvv install .

    - name: Build wheel
      run: |
        pip wheel --verbose . -w wheelhouse_dirty
        auditwheel repair wheelhouse_dirty/xeus_python-*.whl -w wheelhouse

    - name: List wheels
      run: ls wheelhouse

    - uses: actions/upload-artifact@v2
      with:
        name: wheelhouse
        path: wheelhouse/*.whl
        if-no-files-found: error
